name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false # Important!

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build and deploy
        run: |
          npm run build
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}