name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Step 3: Build the Project
      - name: Build Project
        run: npm run build

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "github-actions[bot